### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by pouyarezaei** [ManiMozaffar/linkedIn-scraper#3] opened 2023-04-18 12:44 UTC
jobs from bot has information like {java} but in original page of job is not exist

**Comment by ManiMozaffar** [comment] 2023-04-18 12:51
> jobs from bot has information like {java} but in original page of job is not exist

Hey pouya, I have re-checked and I think that you're mistaken,
1. namespace is java, not {java}. it's also case sensitive, so Java will surely not work, however I'm sending more detailed error in program now, so let's say you want to setup a query for java jobs at backend you'd have to do 
```java and backend```
You may see all namespaces using /show command in telegram bot, or from here
https://github.com/ManiMozaffar/linkedIn-scraper/blob/main/src/services/tech/loaddata.py

2. I've checked java just now and it was working fine, also I ran some test in APIs when I loaded data from loaddata.py that should be initially injected to the program and I can confirm all data in loaddata is present as keyword layer in redis database.

If you found the issue to be solved, please close it.

**Comment by ghost** [comment] 2023-04-19 15:09
Hi, i saw the same bug. I am looking for python jobs. So i found a job alert  on channel and title and detail all was about python,  but the linkedin ad was all about .Net.  ther was nothin about python. 
I saw more bugs like this.

**Comment by ManiMozaffar** [comment] 2023-04-19 15:15
> Hi, i saw the same bug. I am looking for python jobs. So i found a job alert on channel and title and detail all was about python, but the linkedin ad was all about .Net. ther was nothin about python. I saw more bugs like this.

Hi sahar, 
Thanks for reporting this bug, I have better understanding of problem now.
I'll be working on it. I'll have to improve the prompt I'm sending to chatgpt.

for a better outcome temporarily, make your filter more detailed. For example 
```python and backend ```

I'll do a PR to solve this issue, and I'll push that PR to my own deployment, then I'd ask you guys to tell me if problem has been fixed or not.

**Comment by ManiMozaffar** [comment] 2023-04-19 18:30
@saharsdr @pouyarezaei 
Please check if the issue has been solved or not,

**Comment by ghost** [comment] 2023-04-20 22:17
@ManiMozaffar 
مجددا اون مشکل رو مشاهده نکردم. ولی طی بررسی ۳ ۴ تا اگهی اخیر، یکیشون توی کانال تلگرام گفته شده بود ک ویزااسپانسرر NO و اخر پیام ذکر کرده بود ک ویزا اسپانسر شیپ نداره
لینک رو ک مشاهده کردم عینن توی مزایا این دو مورد ذکر شده بود:
Visa sponsership
Relocation package

**Comment by ManiMozaffar** [comment] 2023-04-20 22:23
> @ManiMozaffar مجددا اون مشکل رو مشاهده نکردم. ولی طی بررسی ۳ ۴ تا اگهی اخیر، یکیشون توی کانال تلگرام گفته شده بود ک ویزااسپانسرر NO و اخر پیام ذکر کرده بود ک ویزا اسپانسر شیپ نداره لینک رو ک مشاهده کردم عینن توی مزایا این دو مورد ذکر شده بود: Visa sponsership Relocation package

@saharsdr I'll have to speak in English if you don't mind because some people following this repo are not persian,
I am asking chatgpt to check from database if the company has actually sponsership or not, so the result may not be 100% accurate as for chatgpt's lack  informations sometime, but in this case I can fix it by asking chatgpt to first look into the text to see if any detail is mentioned about relocating and sponsership or not, which I already did!
Please open another issue if in case you have encountered this issue again,
as for the solved issue, I'll close this issue.

**Closed as completed by ManiMozaffar** 2023-04-20 22:23 UTC
Labels: bug, chatgpt
